version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dev-todo
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
      ENV: dev
      DB: postgresql
      DB_USER: todo_user
      DB_PASSWORD: todo_pass
      DB_HOST: db
      DB_PORT: "5432"
      SECRET_KEY: "change_me_in_prod"
      ADMIN_EMAIL: "admin@local"
      ADMIN_PASSWORD: "admin"
      ADMIN_NAME: "Administrator"
    ports:
      - "8000:80"
    volumes:
      - .:/app

volumes:
  db_data:
